---
version: "3.4"
# 3.4 requires Docker engine release 17.09.0+

services:
  d43proxy:
    image: "nginx:latest"
    volumes:
      - ./proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    ports:
      - "${LISTEN_IP:-127.0.0.1}:8080:80"
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - d43enqueue
  d43enqueue:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GITEA_URL=${GITEA_URL}
      - RESTRICT_GITEA_URL=${RESTRICT_GITEA_URL}
    build:
      context: ./enqueue
      dockerfile: Dockerfile-developBranch
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"

networks:
  default:
    external:
      name: tx-net
