name: Deploy image to Docker

on:
  push:
    paths-ignore:
      - 'README.md'  
    branches:
      - master
      - develop
      - release/v*
  release:
    types: [published]

jobs:
  deploy-docker:
    name: Build & Deploy image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Prepare Variables
        id: vars
        shell: bash
        run: |
          DOCKER_PLATFORMS=linux/amd64
          REF=`echo ${GITHUB_REF} | cut -d "/" -f3-`
          echo "REF=${REF}"
          VERSION=${REF}
          # Be default, we use the branch or tag name as the Docker tag
          DOCKER_TAGS="${REF//\//-}"
          DOCKER_FILE=masterBranch
          if [[ "${REF}" == "v"* ]]; then
            # REF is a tag so we create tags for patch, minor and major versions and is the latest production
            VERSION=${REF#v}
            PATCH_VERSION=${REF#v}
            PATCH_VERSION=${PATCH_VERSION%-dcs}
            MINOR_VERSION=`echo ${PATCH_VERSION} | cut -f1,2 -d'.'`
            MAJOR_VERSION=`echo ${MINOR_VERSION} | cut -f1 -d'.'`
            DOCKER_TAGS="${DOCKER_TAGS},latest,${MAJOR_VERSION},${MINOR_VERSION},${PATCH_VERSION}"
          elif [[ "${REF}" == "release/"* ]]; then
            # REF is a release branch so is a beta, qa or latest of this minor version
            DOCKER_TAGS="${DOCKER_TAGS},latest-qa"
          elif [[ "${REF}" == "develop" ]]; then
            DOCKER_FILE=developBranch
          fi
          echo "SETTING DOCKER_TAGS: ${DOCKER_TAGS}"
          echo "DOCKER_TAGS=${DOCKER_TAGS}" >> $GITHUB_ENV
          echo ::set-output name=docker_tags::${DOCKER_TAGS}
          echo "SETTING DOCKER_FILE: ${DOCKER_FILE}"
          echo "DOCKER_FILE=${DOCKER_FILE}" >> $GITHUB_ENV
          echo ::set-output name=docker_file::${DOCKER_FILE}

      - name: Debug
        shell: bash
        run: |
          echo "GITHUB_REF: " ${GITHUB_REF}
          echo "DOCKER_TAGS: " ${{ env.DOCKER_TAGS }}
          echo "DOCKER_FILE: " ${{ env.DOCKER_FILE }}
          echo "steps.vars.outputs.docker_tags:" ${{ steps.vars.outputs.docker_tags }}
          echo "steps.vars.outputs.docker_file:" ${{ steps.vars.outputs.docker_file }}

      - name: Publish Docker Github Action
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          workdir: enqueue
          name: unfoldingword/door43_enqueue_job
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile-${{ steps.vars.outputs.docker_file }}
          tags: ${{ steps.vars.outputs.docker_tags }}
